services:
  mariadb:
    image: mariadb:latest
    # restart: always
    volumes:
      - /mnt/mariadb_data:/var/lib/mysql
      - /mnt/sock:/var/run/mysqld
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - my-network
    ports:
      - "3306:3306"
  nextcloud:
    image: nextcloud:latest
    restart: always
    ports:
      - "8083:80"
    environment:
      - "MYSQL_HOST: mariadb"
      - "MYSQL_DATABASE: nextcloud_db"
      - "MYSQL_USER: nextcloud_admin"
      - "MYSQL_PASSWORD: nextcloud"  
    volumes:
      - /mnt/nextcloud_data:/var/www/html
      - /mnt/sock:/var/run/mysql
    depends_on:
      - mariadb    
    networks:
      - my-network  
  wordpress:
    image: wordpress:latest
    environment:
      - "MYSQL_HOST: mariadb"
      - "MYSQL_DATABASE: wordpress_db"
      - "MYSQL_USER: wordpress_admin"
      - "MYSQL_PASSWORD: wordpress"
    restart: always
    ports:
      - "8081:80"
    volumes:
      - /mnt/wordpress_data:/var/www/html
      - /mnt/sock:/var/run/mysql
    depends_on: 
      - mariadb
    networks:
      - my-network
        

networks:
  my-network:
    driver: bridge
  
volumes:
  nextcloud_data:
  wordpress_data:
  mariadb_data:
  sock:
