- name: Create databases with their users
  hosts: servers
  any_errors_fatal: true
  
  tasks:
    # - name: Installer Pip
      # become: true
      # ansible.builtin.package:
        # name: "pip"
        # state: present
    # - name: installer pymysql
      # become: true
      # ansible.builtin.pip:
        # name: "PyMySQL"
        # state: present
        # 
        
    - name: Creating  nextcloud_db & wordpress_db
      community.mysql.mysql_db:
        check_implicit_admin: true
        name:
          - nextcloud_db
          - wordpress_db
        login_user: root
        login_port: "3306"
        login_password: root
        state: present
        
    - name: Creating wordpress_db's user   
      community.mysql.mysql_user:
        check_implicit_admin: true
        login_user: root
        login_password: root
        login_unix_socket: /mnt/sock/mysqld.sock
        name: wordpress_admin
        password: wordpress
        login_port: "3306"
        state: present
        host: "%"
            
    - name: Create nextloud user
      become: true
      community.mysql.mysql_user:
        check_implicit_admin: true
        login_user: root
        login_password: root
        login_unix_socket: /mnt/sock/mysqld.sock
        name: nextcloud_admin
        password: nextcloud
        login_port: "3306"
        state: present
        host: "%"
    - name: Grant all privileges to wordpress_admin
      community.mysql.mysql_query:
        login_user: root
        login_password: root
        query: "GRANT ALL PRIVILEGES ON wordpress_db.* TO 'wordpress_admin'@'%';"    
    - name: Grant all privileges to wordpress_admin
      community.mysql.mysql_query:
        login_user: root
        login_password: root
        query: "GRANT ALL PRIVILEGES ON nextcloud_db.* TO 'nextcloud_admin'@'%';"    
    - name: validate priviliges
      community.mysql.mysql_query:
        login_user: root
        login_password: root
        query: "FLUSH PRIVILEGES"
              
              
    - name: Associate wordpress_db to wordpresss
      become: true
      ansible.builtin.copy:
        src: /home/khalil/PROJET-DEVOPS/ansible/wp-config.php
        dest: /mnt/wordpress_data/wp-config.php
    
      
      
