- name: Tp noté
  hosts: servers
  become: false
  any_error_fatal: true

  tasks:
  - name: set nameservers
    become: true
    ansible.builtin.linefile:
      path: "/etc/resolv.conf" 
      line: "nameserver 8.8.8.8" 
    
      
